export const DESKTOP_HISTORY_PANEL_BREAKPOINT = 1280
export const DEFAULT_DATE_TIME_FORMAT = 'YYYY-MM-DD HH:mm:ss'
export const PICGO_GUI_GALLERY_MASONRY_COLUMN_COUNT_KEY = 'PICGO_GUI_GALLERY_MASONRY_COLUMN_COUNT'
export const PICGO_GUI_GALLERY_VIEW_MODE_KEY = 'PICGO_GUI_GALLERY_VIEW_MODE'
export const GALLERY_MASONRY_COLUMN_COUNT_DEFAULT = 4
export const GALLERY_MASONRY_COLUMN_COUNT_MIN = 1
export const GALLERY_MASONRY_COLUMN_COUNT_MAX = 10
