export const DESKTOP_HISTORY_PANEL_BREAKPOINT = 1280
export const DEFAULT_DATE_TIME_FORMAT = 'YYYY-MM-DD HH:mm:ss'
export const DEFAULT_DATE_FORMAT = 'YYYY-MM-DD'
export const PICGO_GUI_GALLERY_MASONRY_COLUMN_COUNT_KEY = 'PICGO_GUI_GALLERY_MASONRY_COLUMN_COUNT'
export const PICGO_GUI_GALLERY_VIEW_MODE_KEY = 'PICGO_GUI_GALLERY_VIEW_MODE'
export const GALLERY_MASONRY_COLUMN_COUNT_DEFAULT = 4
export const GALLERY_MASONRY_COLUMN_COUNT_MIN = 1
export const GALLERY_MASONRY_COLUMN_COUNT_MAX = 10
export const PICGO_GUI_GALLERY_ALBUM_SOURCE_KEY = 'PICGO_GUI_GALLERY_ALBUM_SOURCE'
export const CLOUD_ALBUM_PAGE_SIZE = 50
export const GALLERY_CLOUD_LOAD_MORE_THRESHOLD = 200
export const PICGO_GUI_LIFECYCLE_BANNER_DISMISSED_PHASE_KEY = 'PICGO_GUI_LIFECYCLE_BANNER_DISMISSED_PHASE'
/** 渲染端静态资源：PicGo Cloud 图片在 frozen/pending_cleanup/加载失败时使用的占位 SVG 文件名 */
export const PICGO_CLOUD_IMAGE_UNAVAILABLE_SVG_FILENAME = 'cloud-image-unavailable.svg'
