onlyBuiltDependencies:
  - core-js
  - ejs
  - electron
  - electron-winstaller
  - esbuild
  - husky
  - vue-demi

overrides:
  picgo: link:../PicGo-Core

supportedArchitectures:
  cpu: [x64, arm64]
  os: [current]
