// This file is auto-generated by vite-plugin-i18n-types. Do not edit.
import "i18next"

declare module "i18next" {
  interface CustomTypeOptions {
    resources: {
      translation: ILocales
    }
  }
}
