export enum IChalkType {
  success = 'green',
  info = 'blue',
  warn = 'yellow',
  error = 'red'
}

export enum IPicGoHelperType {
  afterUploadPlugins = 'afterUploadPlugins',
  beforeTransformPlugins = 'beforeTransformPlugins',
  beforeUploadPlugins = 'beforeUploadPlugins',
  uploader = 'uploader',
  transformer = 'transformer'
}

export enum IPasteStyle {
  MARKDOWN = 'markdown',
  HTML = 'HTML',
  URL = 'URL',
  UBB = 'UBB',
  CUSTOM = 'Custom'
}

export enum IWindowList {
  SETTING_WINDOW = 'SETTING_WINDOW',
  TRAY_WINDOW = 'TRAY_WINDOW',
  MINI_WINDOW = 'MINI_WINDOW',
  RENAME_WINDOW = 'RENAME_WINDOW',
  TOOLBOX_WINDOW = 'TOOLBOX_WINDOW'
}

export enum IRemoteNoticeActionType {
  OPEN_URL = 'OPEN_URL',
  SHOW_NOTICE = 'SHOW_NOTICE', // notification
  SHOW_DIALOG = 'SHOW_DIALOG', // dialog notice
  COMMON = 'COMMON',
  VOID = 'VOID', // do nothing
  SHOW_MESSAGE_BOX = 'SHOW_MESSAGE_BOX'
}

export enum IRemoteNoticeTriggerHook {
  APP_START = 'APP_START',
  SETTING_WINDOW_OPEN = 'SETTING_WINDOW_OPEN',
}

export enum IRemoteNoticeTriggerCount {
  ONCE = 'ONCE', // default
  ALWAYS = 'ALWAYS'
}

/**
 * renderer trigger action from main
 */
export enum IRPCActionType {
  // config rpc
  GET_PICBED_CONFIG_LIST = 'GET_PICBED_CONFIG_LIST',
  DELETE_PICBED_CONFIG = 'DELETE_PICBED_CONFIG',
  CHANGE_CURRENT_UPLOADER = 'CHANGE_CURRENT_UPLOADER',
  SELECT_UPLOADER = 'SELECT_UPLOADER',
  UPDATE_UPLOADER_CONFIG = 'UPDATE_UPLOADER_CONFIG',
  COPY_UPLOADER_CONFIG = 'COPY_UPLOADER_CONFIG',
  INSTALL_PLUGIN = 'INSTALL_PLUGIN',
  IMPORT_LOCAL_PLUGIN = 'IMPORT_LOCAL_PLUGIN',
  UNINSTALL_PLUGIN = 'UNINSTALL_PLUGIN',
  UPDATE_PLUGIN = 'UPDATE_PLUGIN',
  ENABLE_PLUGIN = 'ENABLE_PLUGIN',
  DISABLE_PLUGIN = 'DISABLE_PLUGIN',

  // version rpc
  GET_LATEST_VERSION = 'GET_LATEST_VERSION',

  // toolbox rpc
  TOOLBOX_CHECK = 'TOOLBOX_CHECK',
  TOOLBOX_CHECK_RES = 'TOOLBOX_CHECK_RES',
  TOOLBOX_CHECK_FIX = 'TOOLBOX_CHECK_FIX',

  // system rpc
  RELOAD_APP = 'RELOAD_APP',
  GET_WINDOW_STATE = 'GET_WINDOW_STATE',
  OPEN_FILE = 'OPEN_FILE',
  COPY_TEXT = 'COPY_TEXT',
  SHOW_DOCK_ICON = 'SHOW_DOCK_ICON',
  SHOW_MENUBAR_ICON = 'SHOW_MENUBAR_ICON',
  SHOW_NOTIFICATION = 'SHOW_NOTIFICATION',

  // picgo cloud rpc
  PICGO_CLOUD_GET_USER_INFO = 'PICGO_CLOUD_GET_USER_INFO',
  PICGO_CLOUD_LOGIN = 'PICGO_CLOUD_LOGIN',
  PICGO_CLOUD_LOGOUT = 'PICGO_CLOUD_LOGOUT',
  PICGO_CLOUD_DISPOSE_LOGIN_FLOW = 'PICGO_CLOUD_DISPOSE_LOGIN_FLOW',
  PICGO_CLOUD_CONFIG_SYNC_GET_STATE = 'PICGO_CLOUD_CONFIG_SYNC_GET_STATE',
  PICGO_CLOUD_CONFIG_SYNC_START = 'PICGO_CLOUD_CONFIG_SYNC_START',
  PICGO_CLOUD_CONFIG_SYNC_APPLY_RESOLUTION = 'PICGO_CLOUD_CONFIG_SYNC_APPLY_RESOLUTION',
  PICGO_CLOUD_CONFIG_SYNC_ABORT = 'PICGO_CLOUD_CONFIG_SYNC_ABORT',
  PICGO_CLOUD_CONFIG_SYNC_SET_E2E_PREFERENCE = 'PICGO_CLOUD_CONFIG_SYNC_SET_E2E_PREFERENCE',

  // picgo cloud album rpc
  PICGO_CLOUD_ALBUM_LIST = 'PICGO_CLOUD_ALBUM_LIST',
  PICGO_CLOUD_ALBUM_DELETE = 'PICGO_CLOUD_ALBUM_DELETE',
  PICGO_CLOUD_ALBUM_UPDATE = 'PICGO_CLOUD_ALBUM_UPDATE',
  PICGO_CLOUD_ALBUM_BATCH_UPDATE = 'PICGO_CLOUD_ALBUM_BATCH_UPDATE',
  PICGO_CLOUD_ALBUM_IMPORT = 'PICGO_CLOUD_ALBUM_IMPORT',
  PICGO_CLOUD_ALBUM_GET_STATS = 'PICGO_CLOUD_ALBUM_GET_STATS',
  PICGO_CLOUD_ALBUM_GET_FILTERS = 'PICGO_CLOUD_ALBUM_GET_FILTERS',
  PICGO_CLOUD_SET_AUTO_IMPORT = 'PICGO_CLOUD_SET_AUTO_IMPORT',
  PICGO_CLOUD_ALBUM_IMPORT_ALL = 'PICGO_CLOUD_ALBUM_IMPORT_ALL',
  PICGO_CLOUD_GET_USAGE = 'PICGO_CLOUD_GET_USAGE',
  PICGO_CLOUD_GET_BILLING_OVERVIEW = 'PICGO_CLOUD_GET_BILLING_OVERVIEW',

  // cloud album event (main -> renderer)
  UPDATE_CLOUD_ALBUM = 'UPDATE_CLOUD_ALBUM',

  // gallery and toolbox rpc
  UPDATE_ALBUM = 'UPDATE_ALBUM',
  GET_ALBUM_MENU_LIST = 'GET_ALBUM_MENU_LIST',
  OPEN_CONFIG_DIALOG = 'OPEN_CONFIG_DIALOG',

  // cross-window sync (renderer -> main -> all other renderers)
  SYNC_ALBUM_SOURCE = 'SYNC_ALBUM_SOURCE',
}

export enum IToolboxItemType {
  IS_CONFIG_FILE_BROKEN = 'IS_CONFIG_FILE_BROKEN',
  IS_ALBUM_FILE_BROKEN = 'IS_ALBUM_FILE_BROKEN',
  HAS_PROBLEM_WITH_CLIPBOARD_PIC_UPLOAD = 'HAS_PROBLEM_WITH_CLIPBOARD_PIC_UPLOAD',
  HAS_PROBLEM_WITH_PROXY = 'HAS_PROBLEM_WITH_PROXY',
}

export enum IToolboxItemCheckStatus {
  INIT = 'init',
  LOADING = 'loading',
  SUCCESS = 'success',
  ERROR = 'error',
}

export enum IStartupMode {
  SHOW_MAIN_WINDOW = 'SHOW_SETTING_WINDOW',
  SHOW_MINI_WINDOW = 'SHOW_MINI_WINDOW',
  HIDE = 'HIDE'
}

export enum IPluginMenuAction {
  ENABLE = 'enable',
  DISABLE = 'disable',
  UPDATE = 'update',
  UNINSTALL = 'uninstall'
}
