/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrayRouteImport } from './routes/tray'
import { Route as ToolboxRouteImport } from './routes/toolbox'
import { Route as RenameRouteImport } from './routes/rename'
import { Route as MiniRouteImport } from './routes/mini'
import { Route as MainRouteImport } from './routes/main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainIndexRouteImport } from './routes/main/index'
import { Route as MainProvidersRouteImport } from './routes/main/providers'
import { Route as MainPluginsRouteImport } from './routes/main/plugins'
import { Route as MainGalleryRouteImport } from './routes/main/gallery'
import { Route as MainDashboardRouteImport } from './routes/main/dashboard'
import { Route as MainCloudRouteImport } from './routes/main/cloud'
import { Route as MainSettingsIndexRouteImport } from './routes/main/settings/index'
import { Route as MainSettingsUrlRewriteRouteImport } from './routes/main/settings/url-rewrite'
import { Route as MainSettingsShortcutsRouteImport } from './routes/main/settings/shortcuts'
import { Route as MainSettingsSettingsRouteImport } from './routes/main/settings/settings'
import { Route as MainSettingsNotificationsRouteImport } from './routes/main/settings/notifications'

const TrayRoute = TrayRouteImport.update({
  id: '/tray',
  path: '/tray',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolboxRoute = ToolboxRouteImport.update({
  id: '/toolbox',
  path: '/toolbox',
  getParentRoute: () => rootRouteImport,
} as any)
const RenameRoute = RenameRouteImport.update({
  id: '/rename',
  path: '/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniRoute = MiniRouteImport.update({
  id: '/mini',
  path: '/mini',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainProvidersRoute = MainProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => MainRoute,
} as any)
const MainPluginsRoute = MainPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => MainRoute,
} as any)
const MainGalleryRoute = MainGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any)
const MainCloudRoute = MainCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsUrlRewriteRoute = MainSettingsUrlRewriteRouteImport.update({
  id: '/settings/url-rewrite',
  path: '/settings/url-rewrite',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsShortcutsRoute = MainSettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsSettingsRoute = MainSettingsSettingsRouteImport.update({
  id: '/settings/settings',
  path: '/settings/settings',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsNotificationsRoute =
  MainSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => MainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRouteWithChildren
  '/mini': typeof MiniRoute
  '/rename': typeof RenameRoute
  '/toolbox': typeof ToolboxRoute
  '/tray': typeof TrayRoute
  '/main/cloud': typeof MainCloudRoute
  '/main/dashboard': typeof MainDashboardRoute
  '/main/gallery': typeof MainGalleryRoute
  '/main/plugins': typeof MainPluginsRoute
  '/main/providers': typeof MainProvidersRoute
  '/main/': typeof MainIndexRoute
  '/main/settings/notifications': typeof MainSettingsNotificationsRoute
  '/main/settings/settings': typeof MainSettingsSettingsRoute
  '/main/settings/shortcuts': typeof MainSettingsShortcutsRoute
  '/main/settings/url-rewrite': typeof MainSettingsUrlRewriteRoute
  '/main/settings/': typeof MainSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mini': typeof MiniRoute
  '/rename': typeof RenameRoute
  '/toolbox': typeof ToolboxRoute
  '/tray': typeof TrayRoute
  '/main/cloud': typeof MainCloudRoute
  '/main/dashboard': typeof MainDashboardRoute
  '/main/gallery': typeof MainGalleryRoute
  '/main/plugins': typeof MainPluginsRoute
  '/main/providers': typeof MainProvidersRoute
  '/main': typeof MainIndexRoute
  '/main/settings/notifications': typeof MainSettingsNotificationsRoute
  '/main/settings/settings': typeof MainSettingsSettingsRoute
  '/main/settings/shortcuts': typeof MainSettingsShortcutsRoute
  '/main/settings/url-rewrite': typeof MainSettingsUrlRewriteRoute
  '/main/settings': typeof MainSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRouteWithChildren
  '/mini': typeof MiniRoute
  '/rename': typeof RenameRoute
  '/toolbox': typeof ToolboxRoute
  '/tray': typeof TrayRoute
  '/main/cloud': typeof MainCloudRoute
  '/main/dashboard': typeof MainDashboardRoute
  '/main/gallery': typeof MainGalleryRoute
  '/main/plugins': typeof MainPluginsRoute
  '/main/providers': typeof MainProvidersRoute
  '/main/': typeof MainIndexRoute
  '/main/settings/notifications': typeof MainSettingsNotificationsRoute
  '/main/settings/settings': typeof MainSettingsSettingsRoute
  '/main/settings/shortcuts': typeof MainSettingsShortcutsRoute
  '/main/settings/url-rewrite': typeof MainSettingsUrlRewriteRoute
  '/main/settings/': typeof MainSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/mini'
    | '/rename'
    | '/toolbox'
    | '/tray'
    | '/main/cloud'
    | '/main/dashboard'
    | '/main/gallery'
    | '/main/plugins'
    | '/main/providers'
    | '/main/'
    | '/main/settings/notifications'
    | '/main/settings/settings'
    | '/main/settings/shortcuts'
    | '/main/settings/url-rewrite'
    | '/main/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mini'
    | '/rename'
    | '/toolbox'
    | '/tray'
    | '/main/cloud'
    | '/main/dashboard'
    | '/main/gallery'
    | '/main/plugins'
    | '/main/providers'
    | '/main'
    | '/main/settings/notifications'
    | '/main/settings/settings'
    | '/main/settings/shortcuts'
    | '/main/settings/url-rewrite'
    | '/main/settings'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/mini'
    | '/rename'
    | '/toolbox'
    | '/tray'
    | '/main/cloud'
    | '/main/dashboard'
    | '/main/gallery'
    | '/main/plugins'
    | '/main/providers'
    | '/main/'
    | '/main/settings/notifications'
    | '/main/settings/settings'
    | '/main/settings/shortcuts'
    | '/main/settings/url-rewrite'
    | '/main/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  MiniRoute: typeof MiniRoute
  RenameRoute: typeof RenameRoute
  ToolboxRoute: typeof ToolboxRoute
  TrayRoute: typeof TrayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tray': {
      id: '/tray'
      path: '/tray'
      fullPath: '/tray'
      preLoaderRoute: typeof TrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolbox': {
      id: '/toolbox'
      path: '/toolbox'
      fullPath: '/toolbox'
      preLoaderRoute: typeof ToolboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rename': {
      id: '/rename'
      path: '/rename'
      fullPath: '/rename'
      preLoaderRoute: typeof RenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini': {
      id: '/mini'
      path: '/mini'
      fullPath: '/mini'
      preLoaderRoute: typeof MiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/providers': {
      id: '/main/providers'
      path: '/providers'
      fullPath: '/main/providers'
      preLoaderRoute: typeof MainProvidersRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/plugins': {
      id: '/main/plugins'
      path: '/plugins'
      fullPath: '/main/plugins'
      preLoaderRoute: typeof MainPluginsRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/gallery': {
      id: '/main/gallery'
      path: '/gallery'
      fullPath: '/main/gallery'
      preLoaderRoute: typeof MainGalleryRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/dashboard': {
      id: '/main/dashboard'
      path: '/dashboard'
      fullPath: '/main/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/cloud': {
      id: '/main/cloud'
      path: '/cloud'
      fullPath: '/main/cloud'
      preLoaderRoute: typeof MainCloudRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/settings/': {
      id: '/main/settings/'
      path: '/settings'
      fullPath: '/main/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/settings/url-rewrite': {
      id: '/main/settings/url-rewrite'
      path: '/settings/url-rewrite'
      fullPath: '/main/settings/url-rewrite'
      preLoaderRoute: typeof MainSettingsUrlRewriteRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/settings/shortcuts': {
      id: '/main/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/main/settings/shortcuts'
      preLoaderRoute: typeof MainSettingsShortcutsRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/settings/settings': {
      id: '/main/settings/settings'
      path: '/settings/settings'
      fullPath: '/main/settings/settings'
      preLoaderRoute: typeof MainSettingsSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/settings/notifications': {
      id: '/main/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/main/settings/notifications'
      preLoaderRoute: typeof MainSettingsNotificationsRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainCloudRoute: typeof MainCloudRoute
  MainDashboardRoute: typeof MainDashboardRoute
  MainGalleryRoute: typeof MainGalleryRoute
  MainPluginsRoute: typeof MainPluginsRoute
  MainProvidersRoute: typeof MainProvidersRoute
  MainIndexRoute: typeof MainIndexRoute
  MainSettingsNotificationsRoute: typeof MainSettingsNotificationsRoute
  MainSettingsSettingsRoute: typeof MainSettingsSettingsRoute
  MainSettingsShortcutsRoute: typeof MainSettingsShortcutsRoute
  MainSettingsUrlRewriteRoute: typeof MainSettingsUrlRewriteRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCloudRoute: MainCloudRoute,
  MainDashboardRoute: MainDashboardRoute,
  MainGalleryRoute: MainGalleryRoute,
  MainPluginsRoute: MainPluginsRoute,
  MainProvidersRoute: MainProvidersRoute,
  MainIndexRoute: MainIndexRoute,
  MainSettingsNotificationsRoute: MainSettingsNotificationsRoute,
  MainSettingsSettingsRoute: MainSettingsSettingsRoute,
  MainSettingsShortcutsRoute: MainSettingsShortcutsRoute,
  MainSettingsUrlRewriteRoute: MainSettingsUrlRewriteRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  MiniRoute: MiniRoute,
  RenameRoute: RenameRoute,
  ToolboxRoute: ToolboxRoute,
  TrayRoute: TrayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
